### ISSUE TITLE
Notifications - Inline Page Banners

### ISSUE THREAD

**Issue by SOjaHPE** [grommet/hpe-design-system#2523] opened 2022-04-12 17:30 UTC
These are inline, meaning not global and not toast, notifications.

They are currently available in grommet: https://storybook.grommet.io/?path=/story/visualizations-notification-status--status&globals=theme:hpe

- [x] connect with Ian to review current Ezmeral usage
- [x] Identify what inline notifications are
- [x] Explore other usages from external design systems
- [x] Gather use cases internally (Ian, Greg, Edgar)
~~- [ ] Explore inline notification taxonomy~~
- [ ] Understand notification center and notification badges

**Comment by SOjaHPE** [comment] 2022-04-12 17:43
Need to follow up with Pooja based on her question posted to the slack hpe-design-system channel
**Contact info**  pooja-amaresha.guttihal@hpe.com

**Question**
> I am looking for guidance on how to visualise multiple persistent banner notifications.
> currently DS suggests to show only one banner at a time. But I am working on a use case where I would want to show around 5 to 6 notifications which are not dismissible and needs user attention as well. We have been using the below pattern to visualise such scenario but it would be helpful if i get any suggestions on the these kind of situations.

**Screen Captures**
![](https://files.slack.com/files-pri/T01LD9FH0JZ-F03B5U8PQ2W/screenshot_2022-04-12_at_6.59.23_pm.png)
![](https://files.slack.com/files-pri/T01LD9FH0JZ-F03ARAM8CMD/screenshot_2022-04-12_at_6.58.59_pm.png)

**Posting the [slack thread conversatio](https://hpe.slack.com/archives/C04LMJWQT/p1649773857102249?thread_ts=1649770482.190929&cid=C04LMJWQT)n** 

> [Vicky Avalos Campos] Thanks for the question. The design system does say that there should be no more than one banner notification at a time. Our guidance also says that all other messages would be located in the notification center. While we don’t have designs of what that would look like, I’m going to tag [@greg.furuiye](https://hpe.slack.com/team/U026RNZD4DB) as he’s been working on what that’ll look like.
> 
> [Pooja Amaresha Guttihal] Thank you [@vicky.avalos](https://hpe.slack.com/team/U027JN13FBJ) for the helpful insight. But in our use case, we don’t want persistent notifications to be missed by the user and currently we only have guidance on banner notifications and not the persistent one’s that the user cannot dismiss until the error is fixed.
> 
> [Matt Glissmann] how does the user resolve the errors?
> My reactions based on limited visibility into the use case:
> It seems as if the error resolutions are a set of tasks or “to dos” and that there should be a dedicated view/screen for “My Tasks” which displays a task queue.
> I don’t believe banner notifications are the best tool to manage that task queue.
> A single associated banner notification can support that task queue with a message “There a 7 errors which need to be resolved …” and link them to the view where those errors may be resolved.
> Again, I don’t have the full context, but my reaction is there might be a more suited tool for the job, such a My Tasks view.
> 
> [Samuel Goff] hi all, I would point out a couple of things:
> The banners “break up” the header from the content. Since the point of a banner is to command your attention, IMO this should bubble up to the top of the main section, just below persistent navbar. This also accomplishes the goal of keeping the header visually associated with the thing it describes.
> Note how Google & Material Design solve dismissible notifications in Google Workspace. They have a menu for notifications, but each of those can be individually dismissed. You can also do a “clear all”
> (edited)
> 
> [Matt Glissmann] ”IMO this should bubble up to the top of the main section, just below persistent navbar.” — Agree, that is the [intended placement](https://design-system.hpe.design/templates/global-banner-notifications) below the NavBar, above the Page Header.
> 
> [Kenny Tran] Hey Pooja, looks like these types of notifications are "inline banners" which we currently do not have guidance on. I wouldn't follow our guidance on Toasts or Global Banners for this too strictly since their use cases are different.
> As for placement, I agree with the above comments about having it under the NavBar and just above the Page Header. Just to clarify, I would not have it underneath the Global Header since that is where Global Banners would live.
> We are currently creating a ticket in the backlog for this and I'll add your name to it for a future followup once we have that guidance. (edited) 
> 
> [Kenny Tran] In the meantime, I'd suggest including anchors if applicable similar to the guidance for [Global Banner](https://design-system.hpe.design/templates/global-banner-notifications#anatomy) so that the user can easily resolve these (especially if you are planning to have them be non dismissable). (edited) 
> 
> [Greg Furuiye]  I’m going to suggest that information notifications should NOT be persistent. [@pooja-amaresha.guttihal](https://hpe.slack.com/team/U026UTV7U1G), you are showing the banner with a close icon which provides the user that opportunity to dismiss the notification, correct?
> Also, it appears that you are showing this information in the service card as well. In an effort to simplify the content on the page, should these types of messages simply remain in the service card and NOT be duplicated at the top of the page?
> I agree with [@kenny.tran](https://hpe.slack.com/team/U027133C276), but I would suggest that these banners are not needed within the existing experience that you are showing.

**Comment by eddieshowcase** [comment] 2022-06-15 18:41
Here is a summary for what Ezmeral team is doing currently with Notifications, Banners, and Alerts etc..  
https://www.figma.com/file/yZyMsoTk6zSn2TgHH257Ea/Ezmeral-Components-V2?node-id=117%3A1336

![Modal feedback](https://user-images.githubusercontent.com/7239901/173901165-df7e12f9-f1d1-446d-b3b0-58aed105a635.png)

![Page feedback](https://user-images.githubusercontent.com/7239901/173901168-839342af-dde0-4efa-8557-0b7ad2e99117.png)

**Comment by eddieshowcase** [comment] 2022-07-11 19:26
Also, after playing with Notification more I have a few more observations...

You might consider having a prop for ‘direction’ … in some cases we want the title inline with message, in others we want it above the message for inline Notifications (not just for Toasts). And I noticed a potential defect, if I pass in a direction = ‘column’ via theme context, the message gets a max width and doesn’t fill the container.

<img width="1128" alt="Screen Shot 2022-07-11 at 3 01 45 PM" src="https://user-images.githubusercontent.com/7239901/178342385-9cf08e1a-2113-45a6-be09-96a6238de803.png">


See this codesandbox here: https://codesandbox.io/s/grommet-v2-template-forked-7mz7rr

For one use case to consider... we have a “EzErrorBoundary” component that we use to wrap major content areas. It will show in case of an unexpected javascript error. This way, our app will never crash and not display or load a page, worst case it loads the page, but the region with a catastrophic error will have this fall back error Notification. Since it tends to spit out whatever javascript error that occurred, I think it would look better in this use case with the title on top.

<img width="1454" alt="Screen Shot 2022-07-11 at 3 04 04 PM" src="https://user-images.githubusercontent.com/7239901/178342517-1afc2261-f6f1-4c81-9cad-8c11a8dca71a.png">

Consider that when using an inline Notification with a long message as designed, the text will wrap UNDER the title, which I think can be OK, but in some use cases like this may not look great.

**Comment by MeganBeierle** [comment] 2022-07-18 18:17
@SOjaHPE 
re: connect with Ian to review current Ezmeral usage

What is Ian's last name? Thx!

**Comment by eddieshowcase** [comment] 2022-07-18 19:51
Erickson is my last name :-)

**Comment by KennyAtHPE** [comment] 2022-07-19 02:45
Keep Chandan updated on our progress.

**Comment by KennyAtHPE** [comment] 2022-07-20 18:17
![image](https://user-images.githubusercontent.com/86075038/180053840-14ab810b-8e10-4d50-b54a-6644a623ae77.png)
Greg is currently working on a project that might need inline banners.

![image](https://user-images.githubusercontent.com/86075038/180053869-849f121f-8250-40ee-b713-a8cf24bbc1e0.png)
Example of how they would be used.

**Comment by KennyAtHPE** [comment] 2022-07-22 19:45
[Notes from our meeting with Greg, Edgar, and Ian](https://www.figma.com/file/xaJICR9J0iqpkoINAWCfS1/Inline-Banner---Notes-from-Edgar%2C-Ian%2C-Greg?node-id=0%3A1)

[External examples of inline banners](https://www.figma.com/file/FGvOd2htjrChVVS2oz73ds/HPE-Notifications?node-id=0%3A1)

**Comment by KennyAtHPE** [comment] 2022-07-22 19:49
Next steps are to explore the taxonomy and anatomy of an Inline Banner. @MeganBeierle will be creating tickets for these. Will be closing this ticket out.

**Closed by KennyAtHPE** 2022-07-22 19:49 UTC
Labels: design system site, design, office hours

**Comment by ericsoderberghp** [comment] 2022-07-22 19:52
> [Notes from our meeting with Greg, Edgar, and Ian](https://www.figma.com/file/xaJICR9J0iqpkoINAWCfS1/Inline-Banner---Notes-from-Edgar%2C-Ian%2C-Greg?node-id=0%3A1)
> 
> [External examples of inline banners](https://www.figma.com/file/FGvOd2htjrChVVS2oz73ds/HPE-Notifications?node-id=0%3A1)

Excellent notes, good content there.

**Comment by vavalos5** [comment] 2022-08-03 21:57
Another use case can be found here: 
https://www.figma.com/file/cCQKjMThmw4I7kf7cnTQFf/branch/45tJI0URPIEkhAnSRFl9KW/ISV-Experience?node-id=333%3A12257
![Screen Shot 2022-08-03 at 2 56 52 PM](https://user-images.githubusercontent.com/62117454/182719670-3dd4818e-1770-4fc3-b258-4259d4065b69.png)
