### ISSUE TITLE
Tabs - Create guidance for tabs with states

### ISSUE THREAD

**Issue by MeganBeierle** [grommet/hpe-design-system#2685] opened 2022-06-23 15:29 UTC

**Comment by MeganBeierle** [comment] 2022-06-23 15:43
While I was researching our tabs for another task I came across an instance that we should provide guidance for. Tabs are sometimes used with a status associated with them to indicate to the user that action is needed for something in that tab. Now that we have responsive tabs there is a concern that important status alerts could be missed if the tabs are hidden behind a scroll action. I have attached screen shots of the treatment that is being used. 

![Screen Shot 2022-06-23 at 9 26 59 AM](https://user-images.githubusercontent.com/107137448/175339783-4d7199db-6861-4ae9-9e99-57706c59b886.png)
<img width="1442" alt="MicrosoftTeams-image (2)" src="https://user-images.githubusercontent.com/107137448/175339814-a765bd58-03a9-4e62-889b-7e381c76ea06.png">

**Comment by ericsoderberghp** [comment] 2022-06-27 01:00
I think we should consider this in a broader context of how "follow the red" would be approached by the GreenLake platform overall. I would like to see how this fits in to some broader stories illustrating various end-to-end user flows that would benefit from this, to ensure we are addressing the overall problem coherently.

**Comment by ericsoderberghp** [comment] 2022-12-07 00:55
Duplicate of https://github.com/grommet/hpe-design-system/issues/2597

**Closed by ericsoderberghp** 2022-12-07 00:55 UTC
Labels: design
