### ISSUE TITLE
Design System Site - "Search" Behavior

### ISSUE THREAD

**Issue by dilippoojari** [grommet/hpe-design-system#1715] opened 2021-07-07 12:18 UTC
### Is this issue related to the design system core library or design system website?

Design System Website - Search

### Expected Behavior
Shouldn’t we allow users to type what they want to search and then show them “no result found” maybe with some context. With the current approach, we are expecting users to be aware of what is available on the Site and then search for it. This may add load on the user when restricted to type against a very common mental modal of regular search behavior.

### Actual Behavior

allow users to type what they want to search and then show them “no result found” maybe with some context. 

The search restricts free type.
The most recent Use case from a New Joiner: Rahul - he was searching for “Notification”... and actually ended up thinking his keyboard konked, as he was not able to type. I did see that this particular example is fixed on the site now.

### URL, screen shot, or CodeSandbox exhibiting the issue

Eg:  If I have to search "Charts" I can only type "Cha" and I am restricted to type "rt". 
<img width="1435" alt="Screenshot 2021-07-07 at 5 31 19 PM" src="https://user-images.githubusercontent.com/87072384/124755568-287fc180-df49-11eb-8e51-69e9d8a12d3b.png">

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Design System version:
- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by ericsoderberghp** [comment] 2021-08-09 16:03
Duplicate of https://github.com/grommet/hpe-design-system/issues/279

**Closed by ericsoderberghp** 2021-08-09 16:03 UTC
Labels: design system site
