### ISSUE TITLE
Design System site times out and causes blank screen

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#1590] opened 2021-04-28 18:04 UTC
Received feedback that when the DS site is left open for a long time (unsure specifically how long it takes, hours v days) the screen goes blanks and prints this console error

![Screen Shot 2021-04-22 at 6 23 28 PM](https://user-images.githubusercontent.com/12522275/116451756-c2bcde00-a811-11eb-8248-e62549fc97f2.png)

**Comment by ericsoderberghp** [comment] 2021-05-03 14:23
Hmm... `jquery`, I wonder if has something to do with the HPE global header.

**Comment by MikeKingdom** [comment] 2021-05-03 15:22
That's definitely the global header. I wonder if it's repeatable or it was a one time thing. Seems like they update it or change it every so often.

**Comment by halocline** [comment] 2021-05-03 16:55
@MikeKingdom Here is the documentation for the new Global Header Service:


**Documentation**
- [Implementation Guide](https://github.hpe.com/rugby/positano/files/42223/common-hfws-quick-js-guide-1.0.0.pdf)
- [Code generator and test page](https://h50007.www5.hpe.com/hfws-test-pages/common-hfws-test-page.php?version=latest.r&cc_ll=us%2Fen&console_mode=true&hide_country_selector=true&hide_main_nav=true&hide_search=true&hide_cart=true&hide_sign_in=true)
- [Video description](https://hpe.sharepoint.com/teams/Capability%20%20Projects/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2FCapability%20%20Projects%2FShared%20Documents%2FDemo%2DCommonHeaderFooterService%2Emp4&parent=%2Fteams%2FCapability%20%20Projects%2FShared%20Documents&p=true&ct=1618943947549&or=OWA-NT&cid=1b9984ec-b3bc-c941-7997-85fb720d27b1&originalPath=aHR0cHM6Ly9ocGUuc2hhcmVwb2ludC5jb20vOnY6L3QvQ2FwYWJpbGl0eSUyMCUyMFByb2plY3RzL0Vla2xmYUhvQ1haRmp5dUFxc3A5eWdBQlh6VU5vczk1RV8wQUQxdk5RaDNhbGc_cnRpbWU9cHFaQWxTc0UyVWc)

**Comment by MikeKingdom** [comment] 2021-05-20 16:52
Closing this since I haven't been able to reproduce this since updating the global header in #1598

**Closed by MikeKingdom** 2021-05-20 16:52 UTC
Labels: bug, design system site

**Comment by samuelgoff** [comment] 2021-06-09 16:57
hey @MikeKingdom, I caught it happening again, while I had https://design-system.hpe.design/templates/table-customization open in the background for a long time. Also, though probably unrelated, I notice a CSP error for an MP4 video trying to load

![Screen Shot 2021-06-09 at 11 52 45 AM](https://user-images.githubusercontent.com/2007084/121397315-d6338c80-c919-11eb-9112-1c47cd213ed9.png)
![Screen Shot 2021-06-09 at 11 53 31 AM](https://user-images.githubusercontent.com/2007084/121397330-d92e7d00-c919-11eb-8e7d-dd60a890aa86.png)
![Screen Shot 2021-06-09 at 11 53 29 AM](https://user-images.githubusercontent.com/2007084/121397343-dc296d80-c919-11eb-8fcc-e7eaeaa774f3.png)
