### ISSUE TITLE
Wizard - Update documentation and visual examples with new copy for Cancel flow

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#2163] opened 2021-12-20 16:54 UTC
Based on #2084 and parent ticket #1884 

- [ ] Update documentation in [Cancellation section](https://design-system.hpe.design/templates/wizard?q=wizard#cancellation)

> It is important to provide the user with an option to "Cancel" or leave the wizard. Place this button on the upper right hand corner of the wizard. When clicked, the "Cancel" button should:
> 
> - Open a Layer that allows the user to confirm they want to cancel
> - Provide two buttons with a clear binary choice (Example: yes or no) and a secondary term that reaffirms the action (Example: stay or leave)
> - The Primary Button should be used to confirm cancellation (Example: "Yes, Leave") and a Secondary Button should give the option to return back to completing the wizard (Example: "No, Stay").

- [ ] Update Visual examples with new copy:

> **Are you sure you want to exit the wizard?**
> Wizard Title
> 
> You have unsaved changes. Leaving this page will cause you to lose all of your progress.
> 
> No, Stay / Yes, Leave

<img width="860" alt="Screen Shot 2021-12-20 at 9 35 40 AM" src="https://user-images.githubusercontent.com/87677275/146809618-9f3a8e5f-eaea-4e9c-b319-9d6e701f239d.png">

**Comment by eddieshowcase** [comment] 2021-12-21 23:39
FWIW - here's what we have right now (though realizing it should be 'medium' and not 'large') in width. I do not prefer the long sentence as a title in your proposed design. 

<img width="965" alt="Screen Shot 2021-09-30 at 11 58 53 AM" src="https://user-images.githubusercontent.com/7239901/147010988-db77362c-8524-4f90-bcbc-7790ca077643.png">

**Comment by eddieshowcase** [comment] 2021-12-21 23:55
And I should explain... what I've told my team is that for a general pattern to follow for modals is this, the Title should be the same as (or least same intent) as the action in which invoked the modal. The Subtitle gives you context, thing, or optional text. Then content is messaging, or "are you sure.." or form etc. Then primary button should be the same as the Title or action that invoked it as well. Following this same pattern, with the exception of renaming the "Cancel" action as "Exit" in the title to avoid the resulting Cancel/Cancel buttons... we get what I'm depicting above in my first comment. Does this make sense? So a general modal pattern example would be this;

<img width="926" alt="Screen Shot 2021-12-21 at 4 53 44 PM" src="https://user-images.githubusercontent.com/7239901/147012349-594c0f54-d5e1-4847-9a41-9478dd5dc46c.png">

just to explain my feedback. I think all modals should follow a general pattern and I wouldn't think having a sentence/messaging in the title as a typical pattern.

Cheers! Happy Holidays!

**Comment by bahriaditi** [comment] 2021-12-22 00:40
cc @CitizenFox 

Thanks for your feedback @eddieshowcase – always appreciate additional use cases!

Some immediate thoughts/ reactions:
- Title: The specific title messaging of the modal will depend on your use case. It should be clear, to the point and with the goal of confirming the action the user is about to take. We are simply providing an example here.
- Body content: this should typically describe the impact of this action
- Buttons: I'm curious to learn more about `Avoid yes/no buttons, it forces a user to have to read and think vs just following the pattern of an action word as a cue - don't have to think.` I can see this being confusing if it was just "yes" or "no", but in this case we are recommending to provide a clear binary choice with a secondary term that reaffirms the action ("No, Stay" / "Yes, Leave")

Happy to pick this discussion up again in 2022 😉  
Happy Holidays!

**Comment by CitizenFox** [comment] 2021-12-22 17:54
I second @bahriaditi's thoughts - thanks for the perspective!

I completely agree that succinct text is a tenet of good messaging, though to @bahriaditi's point, this guidance is not a one-size-fits-all use case. 

Binary choices are simple and clear by design, but yes, this does add more text to read. I don't necessarily think this is a problem though in the case of wizards or lengthier workflows if it gives users a moment of pause to consider the implications of their actions (e.g. "Do I really want to lose all that work?").

That said, you do make a good point for consistency and ease of action, @eddieshowcase, and this is a good discussion for how the design system can provide better content guidance. Let's think on this and reconvene in 2022. See you all there! 🥳

**Comment by eddieshowcase** [comment] 2021-12-22 20:19
Having a message as a sentence for what should be a short concise Title will not scale well. I suppose this could be very succinct as "Exit wizard?" ... but not much longer than that. Consider language translation... many of HPE's products and services ship world wide, when translated, what you have above will wrap 3 or 4 lines! 

Regarding the idea of avoiding yes/no buttons is pretty common in UX. If you use yes/no, the messaging has be well crafted to be clear, but the user still has to read and digest. Also... because of translation this is challenging. 

Even Material Design points this out:
https://material.io/components/dialogs#alert-dialog 

<img width="828" alt="Screen Shot 2021-12-22 at 1 16 25 PM" src="https://user-images.githubusercontent.com/7239901/147150616-3d672798-b391-496b-8afd-31e2ab91ba6a.png">

Again, just my two cents...

**Comment by taysea** [comment] 2022-01-06 19:41
Some thoughts on the guidance:
1. I like that we are moving towards the term "Exit". In that case, should we also rename the button in the Wizard header from "Cancel" --> "Exit"?
2. Regarding Button labeling I agree with @eddieshowcase that we should mirror the language from the title in the primary button of the modal. If we are set on also using "Yes" and "No" in the button labels, I might recommend we do "Yes, Exit" instead of "Yes, Leave" in order to remain consistent with the action being "Exit".

@Keeth-HPe @bahriaditi what are your thoughts here?

**Comment by bahriaditi** [comment] 2022-01-07 03:06
@taysea agree with 2. 

For 1, I would recommend keeping "Cancel" in the Wizard header. "Exit" feels too soft (For ex: With "Exit" I might be unclear about whether or not my changes will be saved or lost)

**Comment by eddieshowcase** [comment] 2022-01-07 17:54
Our general formula for an action/confirmation modal, starting with action clicked i.e. "Delete" .. resulting in a modal with title "Delete Cluster?" with body message of "Deleting a cluster will remove all storage and endpoints. This cannot be undone." Then primary button of "Delete", secondary button "Cancel", covers most all our scenarios and keeps things consistent across the app. 

This wizard cancellation is a very unique/odd use case in that I agree with @bahriaditi that "Cancel" seems to be the appropriate term, but conflicts with our modal formula (we can't have a primary and secondary "Cancel" button). So **just** in this one use case, when the user clicks "Cancel" we switch to the term "Exit" and hope the message in body is very clear. At least that was our strategy in the modal I showed above.

**Closed** 2022-01-07 18:15 UTC
Labels: design system site
