### ISSUE TITLE
NameValueList

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#1718] opened 2021-07-08 14:31 UTC
- [x] #1795
- [x] #1891 
- [x] https://github.com/grommet/grommet/issues/5604
- [x] #1904
- [x] #1906
- [x] #1938
- [x] #1955 
- [x] grommet-site documentation https://github.com/grommet/grommet-site/pull/322
- [x] #1986
- [x] #1989
- [x] #1990

Explore creating a PropertyList or DefinitionList component to handle showing detailed name/value pairs.

In the example below, note that there are many names and that some of the names have different values. This would tend to favor making the names more prominent, to make them easier to scan.

![Screen Shot 2021-07-08 at 7 32 29 AM](https://user-images.githubusercontent.com/11637956/124940360-c497e000-dfbe-11eb-8336-d52304cccf24.png)

In the example below, there are only a handful of names and the values are unique. This would tend to favor making the values more prominent.

![Screen Shot 2021-07-08 at 7 42 11 AM](https://user-images.githubusercontent.com/11637956/124941902-037a6580-dfc0-11eb-82db-055e59d18a7c.png)

In this example, the number of names is short but some of the values are multi-line. In this case, having the values more prominent would likely be too heavy.

![Screen Shot 2021-07-08 at 8 23 12 AM](https://user-images.githubusercontent.com/11637956/124948658-be593200-dfc5-11eb-89a1-73ecd3f422b6.png)

Some things to consider:
- should names be more prominent or should values be more prominent?
- how to handle a combination of short and long names? wrap names at a max width?
- responsive behavior

**Comment by eddieshowcase** [comment] 2021-08-04 17:41
I was recently looking for a way to present properties like this. I thought we could use the 'plain' prop (to remove the border treatment) plus the 'readOnly' prop on a TextInput component for this type of use case as well. Then you can list and structure these items in the same way you might structure them in a form. However, it seem the 'plain' prop is not working as intended. Maybe this doesn't support your use cases here that are more of a true vertical list. But FWIW, here is an example of what I'm talking about (see 'plain / metadata') TextInput example here: https://koala-bandits.github.io/nrcs-design-system/components/kitchen-sink/textinput

**Comment by eddieshowcase** [comment] 2021-08-04 17:52
For a bit more context, I have use cases like this screenshot to show property: value type metadata, but not necessarily in a list. 
<img width="1054" alt="Screen Shot 2021-08-04 at 11 50 28 AM" src="https://user-images.githubusercontent.com/7239901/128230071-527e68e9-2ff5-41da-83a2-57f94ec2645c.png">

**Comment by bahriaditi** [comment] 2021-08-04 18:03
> I was recently looking for a way to present properties like this. I thought we could use the 'plain' prop (to remove the border treatment) plus the 'readOnly' prop on a TextInput component for this type of use case as well. Then you can list and structure these items in the same way you might structure them in a form. However, it seem the 'plain' prop is not working as intended. Maybe this doesn't support your use cases here that are more of a true vertical list. But FWIW, here is an example of what I'm talking about (see 'plain / metadata') TextInput example here: https://koala-bandits.github.io/nrcs-design-system/components/kitchen-sink/textinput

Thanks for providing this use case @eddieshowcase! What product/platform design are these screenshots from?

I see what you are saying about modifying the TextInput component. However, I am also trying to solve for vertical list use cases, which seem to be a requirement for some team members. I am still researching and thinking about best ways to move forward, especially in terms of which existing component this could be a variant for (given the diverse use cases). I'll reach out to you if I have more questions. Until then stay tuned!

**Comment by eddieshowcase** [comment] 2021-08-04 18:15
> 
> Thanks for providing this use case @eddieshowcase! What product/platform design are these screenshots from?
> 

These screenshots are from newish proposed designs for new Ezmeral UI. We have several use cases for something like this. That screenshot is the last 'Review' step in a wizard. We have similar proposed cards with metadata like this for dashboard pages as well as in a drawer showing some selections, totals, or metadata.. 

<img width="257" alt="Screen Shot 2021-08-04 at 12 10 02 PM" src="https://user-images.githubusercontent.com/7239901/128232998-37c3f94f-da19-4e49-a49e-1e5e094331e2.png">
<img width="328" alt="Screen Shot 2021-08-04 at 12 11 46 PM" src="https://user-images.githubusercontent.com/7239901/128233000-0b99e271-4e35-48ae-8210-b4dddebdbead.png">
<img width="603" alt="Screen Shot 2021-08-04 at 9 13 07 AM" src="https://user-images.githubusercontent.com/7239901/128233086-76bd4745-f9d1-4b0a-9e68-1e01e5d85817.png">

**Comment by eddieshowcase** [comment] 2021-08-13 18:41
Another use case example with some variants...
<img width="1328" alt="Screen Shot 2021-08-13 at 12 41 16 PM" src="https://user-images.githubusercontent.com/7239901/129404596-ae8ccd3f-768c-4afe-888e-841ee250a7ca.png">

**Comment by bahriaditi** [comment] 2021-08-19 22:57
Wrapping up the "explore" phase of this ticket with following notes:

- Collected use cases across platforms to illustrate component need and context
- Studied component anatomy to define key building blocks
- Together with @halocline , identified areas where styling flexibility may be needed (label positioning, typography scale, weight, layout etc.)
- After speaking with @ericsoderberghp leaning towards including this component within the "Visualizations" section of the HPE Design System (rather than layout) FYI @halocline 
- Found a good documentation example for a similar component on [Siemens MindSphere design system](https://design.mindsphere.io/patterns/key-value.html)

[WIP Figma file here](https://www.figma.com/file/Ny7rYK5gI5VO4PtZsq6vGC/?node-id=0%3A1)

**Comment by bahriaditi** [comment] 2021-09-09 18:00
Reopening and moving this parent ticket to "Inspiration point" so we can keep all related notes in one place.

Additional notes from @eddieshowcase as it relates to Ezmeral (via Slack):

"[...] Built a design system EzMetaInfo component, you can pass in data, and an optional title… it renders metadata via a responsive grid. Then a dev can throw this into any container, modal, card, drawer and it will do the right thing. We like this, and designers like the idea of having similar presentation of small text label on top / form-text value below as in a Form. _[GIFF attached]_

This way, we can present static metadata in a form and it works formats nicely with other Form labels/inputs.
And so far, we haven’t had a use-case or need for vertical left-right property lists (yet). Even though I think a vertical left-right property list is good to have in the design system, I think you should also have something like what we did (and honestly feel its more useful and readable in some cases over a vertical list). 

Both presentations of property lists are often provided in design systems via a variant of ‘plain’ ‘readonly’ Form controls, for example Bootstrap: https://getbootstrap.com/docs/5.1/forms/form-control/#readonly-plain-text, with this, you can produce vertical left/right property lists, or top-label/bottom-plain-text presentations and lay them out in a vertical or grid Form layout. This is because many times properties are intermingled with editable Form fields. Another example: https://koala-bandits.github.io/nrcs-design-system/components/kitchen-sink/textinput. 

One suggestion I gave to Taylor/Eric was to make the ‘plain’ prop on TextInput component work as it suggests: https://v2.grommet.io/textinput#plain, but turns out borders still appear when in a Form… but from a dev standpoint, we could have used this to achieve our MetaInfo component, but had to create our own because this ‘plain’ thing didn’t work. For your vertical left/right property lists, you can use a List component as the base."

![metaInfo](https://user-images.githubusercontent.com/87677275/132738442-5afcf574-94ad-499e-819a-0cec2c110c60.gif)

**Closed** 2021-11-15 16:57 UTC
