### ISSUE TITLE
Button - post submit busy indication

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#1321] opened 2020-12-14 16:59 UTC
[Figma File](https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=7202%3A14889&t=PZyBsy0hvqGBkqDf-1)

Ideate on how we should implement Button transitions, what the Button does after click to indicate that something is happening in the background. Should we enhance grommet with something like `<Button busy />` or `<Button progress={27} />`?

## Deliverables

- [x] 3-10 design ideations
- [x] review with the team
- [x] choose a direction
- [x] create follow on issues as needed

**Comment by britt6612** [comment] 2022-03-23 15:53
Brought up in office hours 3/23 
Click on Add Button then have that change to a Adding with a Spinner

**Comment by britt6612** [comment] 2022-03-23 20:02
Sam shared these screen grabs with me

![Screen Shot 2022-03-23 at 2 47 39 PM](https://user-images.githubusercontent.com/42451602/159785709-21bd64e1-4fe7-42b8-b9e5-22dfed1d0d85.png)

![Screen Shot 2022-03-23 at 2 48 05 PM](https://user-images.githubusercontent.com/42451602/159785784-08487067-2a31-4c0e-8427-8457eb757265.png)

**Comment by ericsoderberghp** [comment] 2022-03-23 21:00
I have this vague recollection that we didn't want to go the direction of putting a Spinner inside the Button for this. But, I can't remember the details. I'm mentioning this here to check back on it later.

**Comment by samuelgoff** [comment] 2022-04-18 18:58
Hey @ericsoderberghp & @britt6612, the use case is we are on a page or in a modal/layer that kicks off a request that can sometimes take a little while to complete & may return a form submission error. For this reason, we don't want to take the user out of the modal or page, until we get a success returned from the back-end.

Whether it's a spinner, 3 dots animating (`...`) or any other variation. I don't really care so much about the specifics, as long as we show some sort of animated indicator to provide feedback to the user that:

1. their request has been received by the UI
2. the UI is working on doing what they asked us to do with the submit button
3. it hasn't finished yet

The advantage of the `Spinner` approach is consistency with other areas of the UI that already use a `Spinner` component, whether it's waiting for data to fetch for a `DataTable` or a `Card` or `Widget`. Why reinvent the wheel to provide this feedback?

Additionally, you can easily pass the `Spinner` into the `icon` prop for the `Button`, so implementation is dead simple.

If you don't like the spinner appearing to the right, there are many other design variations, and [Ladda](https://github.com/hakimel/Ladda) provides a number of these examples to draw from on their [live demo](https://lab.hakim.se/ladda/). In particular, the `zoom-in` example can be combined with an overlay-type approach, wherein the label is retained but reduced in opacity (as occurs when you disable a button already), and the spinner is superimposed, centered, against the button background.

@halocline yes, absolutely, I have code that's [already implemented](https://github.com/hpe-hcss/metal-app/blob/main/src/components/SubmitButton.js) in GLC & would be happy to share.

**Comment by eddieshowcase** [comment] 2022-05-24 21:44
<img width="723" alt="Screen Shot 2022-05-23 at 11 34 09 PM" src="https://user-images.githubusercontent.com/7239901/170137509-1499acd7-ed7d-4bef-8603-e6b094becf24.png">

**Comment by eddieshowcase** [comment] 2022-05-24 21:44
![loadingButton2](https://user-images.githubusercontent.com/7239901/170137539-d42dadd6-9003-46c4-a06d-07e3edbe5dc8.jpg)
![loadingButton1](https://user-images.githubusercontent.com/7239901/170137543-bd14a13a-8627-41a8-b25a-96f616a01d36.jpg)

**Comment by samuelgoff** [comment] 2022-07-01 17:31
> <img alt="Screen Shot 2022-05-23 at 11 34 09 PM" width="723" src="https://user-images.githubusercontent.com/7239901/170137509-1499acd7-ed7d-4bef-8603-e6b094becf24.png">

@eddieshowcase thanks for sharing these! While I think a spinner inside the button is the best approach, I feel it important to emphasize 2 different considerations:
- If you put the spinner to the left, you reposition the label horizontally. When it appears or disappears, this appears to be "jank" for the user. So positioning the spinner **_after_** the label is less disruptive to the user, because it doesn't have to reposition the label itself in order to accommodate.
- If the button is disabled, the spinner should "look" disabled. This helps strike a balance between grabbing the users attention vs suggesting the button is "active" (not disabled), and also turns down the volume a bit

These were among the considerations that led to my design decisions.

**Comment by ericsoderberghp** [comment] 2022-11-15 22:52
Some thoughts on form submission scenarios:
- in general, back-end API calls should be designed and built to be responsive, < 200 ms. In these cases, it wouldn't be appropriate to show a spinner so briefly that it flickers in and right out.
- if a back-end action does require some time to process, like allocating some resources, then the API should be built to be asynchronous, so the response would be just "received" and quick with a subsequent mechanism to track the result later, perhaps via a "task".
So, it would be helpful to understand a specific API action flow a bit more to think about what the right guidance would be.

**Comment by KennyAtHPE** [comment] 2022-12-06 16:54
@Keeth-HPe here are [some comments](https://www.figma.com/file/Lh01flLH73cFNGZiFxEFth/HPE---Office-Hours?node-id=2268%3A36302&t=5DeF8PKlDFZGXAx0-1) we had on some of the designs in this ticket.

There's also a comment about possibly using inline notifications as an alternative approach that could be interesting to explore.

**Comment by samuelgoff** [comment] 2022-12-06 17:35
> Some thoughts on form submission scenarios:
> 
> * in general, back-end API calls should be designed and built to be responsive, < 200 ms. In these cases, it wouldn't be appropriate to show a spinner so briefly that it flickers in and right out.
> * if a back-end action does require some time to process, like allocating some resources, then the API should be built to be asynchronous, so the response would be just "received" and quick with a subsequent mechanism to track the result later, perhaps via a "task".
>   So, it would be helpful to understand a specific API action flow a bit more to think about what the right guidance would be.

Hey @ericsoderberghp you bring up some great points. The issue is that API performance is a WIP, so while the ideal is < 200 ms, we currently have no guarantees. In real-world application, we have to allow for people to have slow network connections, back-end systems to intermittently slow down, etc. IMO, the design shouldn't be an all-or-nothing type of approach. It should be flexible enough to handle what is likely the 80% use case.

In ours, creation/addition/provisioning of a compute group, compute instance, or other hardware resource takes time (seconds or minutes), so all of those processes are kicked off asynchronously & toast or other feedback show up as needed.

However, for the immediate task at hand -- knowing whether a form's "submit" succeeds or produces errors -- it is important to avoid closing the modal & forcing a context switch. Bear in mind that the ONLY error preventing the user from succeeding might be that they inadvertently chose a resource name that already exists. It would be incredibly frustrating to close a form (especially one that's time consuming, such as create compute instance), only to have a toast alert show up 2 seconds later that says "create compute instance failed". Meanwhile, if we leave the the form open, it is a much better UX to have to the error show up inline, and there are [important accessibility requirements that allow the user to address a form's problem state & resubmit](https://webaim.org/techniques/formvalidation/#error) (aka "error recovery").

Of course, the ideal is to detect an issue pro-actively by providing validation upon blur of each field. So if a resource name cannot be used, the user is provided a validation error ASAP when they finish editing that value, since their attention will still be there. Unfortunately, in some situations this may require additional APIs to support checking whether a name is available, and it may be unsustainable to create a separate endpoint for each and every form. An alternative might be to enhance existing APIs to allow a "preflight" parameter that allows the back-end to **_validate_** & respond without actually acting further on the form submission.

**Comment by vavalos5** [comment] 2022-12-13 14:44
[Adding Keeth's Figma file here]([Figma File](https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=7202%3A14889&t=PZyBsy0hvqGBkqDf-1)). These are looking great Keeth!

**Comment by Keeth-HPe** [comment] 2022-12-16 16:54
Hello Team,
Here are some of the ideations I have worked on so far. @samuelgoff & @KennyAtHPE @ericsoderberghp  Thank you for your feedback on version 1 of ideations. I've tried to implement your thoughts/suggestions. 
Please take a look at the prototypes and share your thoughts as comments

Prototype Link :https://www.figma.com/proto/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?page-id=667%3A385&node-id=7363%3A19837&viewport=271%2C733%2C0.02&scaling=contain&starting-point-node-id=7363%3A19837&show-proto-sidebar=1

File link : https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=7256%3A17461&t=J3UKS7baOXUqbzMk-1

**Comment by SOjaHPE** [comment] 2023-01-04 05:49
@Keeth-HPe Here was some feedback on your prototypes as far as next steps.

- For the Flow 9 prototype - we wanted to avoid concepts that forced the layer container to have to grow or shift to show the busy indicator visualization or messaging. This could cause some collisions or strange display behaviors in some instances.
- The general consensus was to push the ideation for concepts similar to what you designed for the Flow 10 prototype. See if you can put sometime into fun concepts, maybe possible influences from recent rebranding elements/assets while keeping the following in mind -
     1. Encapsulate the busy indicator within the bounds of the button container.
     2. Avoid dynamically changing the button label text string that could force the width of the button to change.

Excited to see what you come up with.

**Comment by Keeth-HPe** [comment] 2023-01-05 04:18
Adding the link to the latest prototyped ideations: https://www.figma.com/proto/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?page-id=667%3A385&node-id=7499%3A22779&viewport=-112%2C516%2C0.03&scaling=scale-down-width&starting-point-node-id=7499%3A22779&show-proto-sidebar=1

**Closed** 2023-01-06 15:03 UTC
Labels: design, office hours
