### ISSUE TITLE
Capitalization - Provide guidance for headings, forms, form field labels, placeholders, buttons, etc.

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#2610] opened 2022-05-18 17:26 UTC
Continuation of https://github.com/grommet/hpe-design-system/issues/937

[Brand Writing Style Guide](https://brandcentral.hpe.com/brand-central/content/writing-style)

- [ ] Clarify the content executed in #937.
- [ ] Fill in gaps such as form-field labels and other items mentioned in this [Slack thread](https://hpe.slack.com/archives/C04LMJWQT/p1652817486734089).
- [ ] I believe there may be guidance which speaks to button label casing.
- [ ] Consider creating a dedicated page to casing and capitalization which would consolidate all information and could be cross-referenced from other areas of the site.
- [ ] Once guidance is provided, create an issue to audit the Design System site content and examples for areas which need proper casing. This will likely need to be a "tracking issue" with sub-issues.

**Comment by dahliaferrer** [comment] 2022-05-23 17:16
@ericsoderberghp @CitizenFox While we do have a writing style guide as well as a design style guide and it's good for developers/designers to be familiar with it and consult it, it's probably a lot to ask them to be ultimately responsible for ensuring their work adheres to all of the nuances of the guides. In sum: it would be best that it is always looked at by a quality assurance and copywriter before it gets released. 

I do wonder if there's anyone on the brand team could do something like that or if we could share in the **_duties_** at least until we get people who are dedicated to QA? One person from our team and one person from the brand team? 

Who is responsible for writing and updating this document? Who could I speak with?
https://www.figma.com/exit?url=https%3A%2F%2Fdesign-system.hpe.design%2Fcomponents%2Faccordion%3Fq%3Dacco

**Comment by CitizenFox** [comment] 2022-05-27 22:07
In regards to the first two points, these are sound suggestions @dahliaferrer though maybe worth a separate discussion to map out where content wants/hopes to go. If you have the time, let's meet up next week and draw up an initial plan to share with @SOjaHPE.

**Comment by dahliaferrer** [comment] 2022-06-16 16:35
I had a convo with Paula in Brands and she confirmed that HP has always stated that we should be using "sentence case" (capital first letter, all other letters in lowercase) and, in fact, it is in the guide! But they had no quality control or enforcement capabilities in HPE, so HPE for some reason used title case (Where Almost Every Letter is Capitalized).

Sentence case, in general, is easier to read versus "title-casing" everything unnecessarily adds importance, urgency and stress.

Jeff added me to the "Reviews" Slack channel and am a required reviewer. 

Also, I volunteer to help clean up our apps/screens, retroactively, but it will be slow-going.

- [ ] Set up a system (with whom? Jeff?) for me to go in retroactively into apps/screens 

- [ ] Jeff should mention to the teams that they should give me Editing rights.

**Comment by dahliaferrer** [comment] 2022-06-21 21:23
It turns out the Voice & Tone already has guidance on capitalization. It's just it's not really being followed. I'm getting the word out to give me editing permissions in Figma files to help dev/designers with current projects.

I've Slacked Jeff and asked him how best for me to go in and retroactively apply sentence case capitalization to our UIs.

**Comment by dahliaferrer** [comment] 2022-07-05 17:22
Not surprisingly, there's a bit of resistance, especially to giving me editing rights. I won't push on that since it's their documents, even if it will make it a lot easier for them. This sounds like it's an individual choice on the part of designers. Fears include, but are not limited to, me writing something too long for the constraints of the space available. I assured Jeff that I would only change typos and small things by editing myself and would always leave a comment for the designers when there are bigger changes, but I'm sure there are other fears and maybe there's some trust-building that needs to happen.

We do need to start moving things to sentence case, but designers, rightfully, keep referencing our current guidance when I note sentence case changes. So, we should edit the guidance we've written itself!

- [ ] Reference HP brand guides for sentence case in OUR guide (meaning: we must update the guide per se)
- [ ] Add any research on sentence vs title case
- [ ] Make a note in Slack channels about the change along with the fact that I'll be reaching out to designers to see how we can retroactively make changes.

**Comment by dahliaferrer** [comment] 2022-07-12 20:50
Have made edits to 2 guidance that mentioned the "title case." My edits don't mention the brand guide, which is what I've based the guide, but I might add them if Eric/Taylor/Scott think it's a good idea. Sent PR to Eric and Taylor.

**Comment by dahliaferrer** [comment] 2022-07-18 16:45
Here's the PR
https://github.com/grommet/hpe-design-system/pull/2701

Eric approved and "merged," i.e. published the guidance. They were just minor changes to the text.

We will create "issues" in Github for tasks related to implementation.

**Closed by dahliaferrer** 2022-07-18 16:45 UTC
Labels: content / documentation
