### ISSUE TITLE
Tabs - updates based on A/B test outcomes

### ISSUE THREAD

**Issue by MeganBeierle** [grommet/hpe-design-system#2828] opened 2022-08-15 18:12 UTC
General idea is to go full black with the active Tab lower border stroke color.

## Deliverables

- [x] update Figma Tabs component stroke color
- [ ] update grommet-hpe-theme stroke color

**Comment by MeganBeierle** [comment] 2022-08-15 18:16
After reviewing the UX study we have determined that it is not an issue for users to know what tab is selected in our design system site. Our developers are also concerned about a visual shift that will happen to all of the tabs because of the change in size of the font states. We do however see that there is room for improvement and that we can increase the speed of comprehension. We will explore making a change to the tab area where the stroke becomes more pronounced upon selection. 

- [ ] Create design options for selected tab

**Comment by MeganBeierle** [comment] 2022-08-15 22:59
https://www.figma.com/file/Kp4dWyhUTnKIJ1Cg5CoL9o/HPE-Tabs-Component?node-id=4317%3A40074
Hi @ericsoderberghp and @bezAdane 

In looking at some design options for the active tab state, I think a black stroke would make a big difference. Please see 4 options and the current tab design to compare in the figma file and let me know what you think.

**Comment by ericsoderberghp** [comment] 2022-08-16 02:23
I find myself gravitating towards the first and fourth options. Might be worth checking with a developer on whether one or the other is notably easier from the implementation side.

**Comment by bezAdane** [comment] 2022-08-16 02:37
I too like the 1st and 4th design! May be leaning a little toward 1st design :)

**Comment by MeganBeierle** [comment] 2022-08-22 17:34
@ericsoderberghp @bezAdane Hi team! Brittany took a look at the options and said the #1 would be easier to implement than #4. Should I put in a task to get this change made?

**Comment by ericsoderberghp** [comment] 2022-08-22 18:07
yes!

**Comment by vavalos5** [comment] 2022-09-22 21:57
@MeganBeierle In reviewing this ticket, it looks like Figma has already been updated to match what is on the DS site. Can you confirm please. Thanks!

**Comment by vavalos5** [comment] 2022-09-22 22:02
I've confirmed with Megan that these changes had already been made by Beza. Also confirmed that they're implemented in Grommet and DS site. Closing :)

**Closed by vavalos5** 2022-09-22 22:02 UTC
Labels: design, Implement
