### ISSUE TITLE
Proposal for Figma order of operations for tokens publishing

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#4123] opened 2024-08-20 22:54 UTC
Once tokens are ready, we also want to be able to publish our Figma component library consuming the tokens. From a testing standpoint, we have already mapped tokens to the atomic HTML elements.

We want to publish a "token" version of our components

Deliverables:
- [x] Answer the following question: When it comes to publishing a "token" version of our components, can we publish the current components with tokens mapped to them? Do we need to refactor before publishing? How large of an effort do we expect this will be?
   - Considerations:
      - From a designer experience perspective, if we publish the "token" version of components as they are, then refactor later, what breaking changes will this cause for designers?
      - If we need to refactor first, do we have to refactor everything? Can it be done in a waterfall fashion?

**Comment by oliverHPE** [comment] 2024-09-03 10:12
Having considered several factors, we've tentatively decided to rebuild/refactor the HPE Figma components prior to tokenising. Considerations include:

- The entire library’s features — “All the things” — can be impacted.
- Upgrading requires attention yet may or may not be effortful, depending on the scale of breaking change, tooling and regression required.
- Changes require aligning with partners like brand and/or architecture.
- Because things are breaking, it’s time to revisit a backlog to do things a system couldn’t do before so as to not break things.
- Other system work slows or stops, crowded out by the focus on updating “all the things” and enabling adoption.
- Rebuilding first reduces breaking changes within designs
- Tokens v1 is being released in a few months, giving us time now to rebuild before tokenising.

Regarding the update process, at this point we've concluded that it would be best to create a second v2 HPE component library, to work on the component rebuild, refactoring and tokenisation. The size of the work will affect everything, and using a v2 library will limit the impact on designers work, and reduce risk overall. The v1 Figma library will be maintained during this process. V2 library will first be release as an Alpha.

**Comment by oliverHPE** [comment] 2024-09-03 10:13
Figma file relative to this work: https://www.figma.com/board/3bniQNKzhmtIC38JIR5kEa/Tokens-and-Figma-library?node-id=0-1&t=awTw9Mas7q4tIR0s-1

**Closed** 2024-09-03 15:09 UTC
Labels: Owner:Design, Where:Figma, BigThing:Tokens
