### ISSUE TITLE
Evaluate hpe-global-header

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#2996] opened 2022-10-24 16:19 UTC
This issue is to set a baseline for future work to optimize the hpe-global-header web component.

## Deliverables
- [x] verify whether styled-components pollutes the global styles when the header is delivered as a web component
- [x] make some measurements of the time to initial render, time to completion of hydration, size of downloaded assets, etc.

**Comment by taysea** [comment] 2022-10-25 19:42
## Set up
- url: https://hpe-global-header.netlify.app/
- using Mac Chrome Developer Tools

![Image](https://user-images.githubusercontent.com/12522275/197864111-127f8a12-91f4-45c9-ba7e-919136fc2ac6.png)

## Size of download assets:
- hpe-global-header.js: 2.1MB
- HPE GreenLake badge: 4.1kB
- MetricHPEXS-Regular.woff2: 25.9kB
- MetricHPEXS-Bold.woff2: 271.kB

## Loading metrics
- DOMContentLoaded: 335.7ms
   - Indicates the browser has finished parsing the document, but other resources such as images and stylesheets may/may not have been downloaded
- Load event: 767.9ms
   - The load event fired will occur once all the initial resources (images, stylesheets, JavaScript) have been downloaded.

## hpe-global-header.js
- start: 163ms
- duration: 257.64ms

![Image](https://user-images.githubusercontent.com/12522275/197864660-ce85900a-9f0d-431a-ae13-7981911ce6a6.png)

## hpe greenlake badge request
- start: 563ms
- duration: 125.17ms
- 
![Image](https://user-images.githubusercontent.com/12522275/197864782-8d2a0305-de58-46a9-b8f6-84f41154673d.png)

## MetricHPEXS Regular
- start: 563ms
- duration: 126.03ms

![Image](https://user-images.githubusercontent.com/12522275/197864864-ece87517-5da2-4ae4-ae8f-f644ca4f2560.png)

## MetricHPEXS Bold
- start: ~613ms
- duration: 120.75ms

![Image](https://user-images.githubusercontent.com/12522275/197865110-5c94baf6-28ab-461e-92c1-1031fa34ceb7.png)

**Comment by taysea** [comment] 2022-10-25 21:48
It also does seem like there is potential for styled-component pollution when the global header script is included. For example, in the Design System site, this warning appears in the console:

![Image](https://user-images.githubusercontent.com/12522275/197888563-2e84bc8a-c4d6-414b-bb46-671bd7e55599.png)

**Comment by ericsoderberghp** [comment] 2022-10-26 03:50
Thanks for the results.

Some initial reactions:
- I'd next want to know what makes up the 2.1MB javascript file. That seems rather large for the amount of content in the header. Some possible next directions on this front: https://medium.com/a-young-devoloper/analyzing-and-reducing-react-bundle-size-bb2d2577b22a
- How is it that styled-components within a web component pollute the CSS namespace? I thought we'd seen something about web components keeping CSS isolated. What are we not understanding here?
- Can we inline the logo SVG instead of loading it as a separate file?
- Would NextJS be a good solution to pre-render the HTML such that it could render right away without having to do any React hydrating? How would this work for a web component anyway?
- Would this be of any help? https://reactjsexample.com/react-18-streaming-made-fully-fledged-and-easy/

Just capturing some ideas for future next steps.

**Comment by taysea** [comment] 2022-10-27 18:08
Some follow-ons regarding style pollution.

## Shadow DOM + styled-components pollution

I learned that web components doesn't automatically implement its contents in the shadow DOM. Instead, this must be done manually.

I have implemented the Shadow DOM in 2 approaches:
1. Using an additional package called `react-shadow` and implementing in Header.js: https://github.hpe.com/grommet/hpe-global-header/pull/4
   - Resource: https://codesandbox.io/s/determined-jepsen-c1md0?file=/src/App.js
2. Directly in the index.js for the web-component, but this has some limitations with where any portal related content rendering to Light DOM as plain HTML: https://github.hpe.com/grommet/hpe-global-header/pull/5

I confirmed that:
- When implemented in the Light DOM, styled-components namespace pollution **can occur**.
- When implemented in the Shadow DOM, styled-components namespace pollution **cannot occur**. This is because the style tag is scoped specifically to the Shadow DOM root by the use of styled-components `StyleSheetManager` which is targeted to the Shadow DOM.

## Shadow DOM + `@font-face`

A general limitation of the Shadow DOM in general (separate from Grommet or styled-components specifically) is that it is unable to load custom `@font-face` from style sheets internal to the Shadow DOM. So, it seems that the font faces will need to be loaded into the main document head (handled in both of the above PRs). This doesn't seem like a huge concern since the micro-frontends should all be using the same MetricHPE anyway.

## Grommet limitations in the Shadow DOM

One behavioral limitation I found with Grommet in the Shadow DOM is that certain Layer/Drop behaviors (such as automatically closing when another Drop opens) or restoring focusing to the previously focused element when a Drop closes via "esc" are lost. Instead, a Drop stays open even when a subsequent opens, or focus is restored to the start of the document when a Drop is closed via "esc".

I believe this might be due to how some of grommet DOM utils work. There have been some other shadow DOM related issues in Grommet over the last year or so similar to what I ran into here.

https://user-images.githubusercontent.com/12522275/198365802-3d8bda96-d4f8-4c3b-9fa5-3a99ed82ac7b.mov

**Comment by taysea** [comment] 2022-10-27 18:33
Re: bundle size, I realized we weren't doing `--mode production` on the webpack build. When we do this, the file size is reduced to 421kB. PR filed: (TBD)

**Comment by taysea** [comment] 2022-10-27 18:46
With the webpack build in production mode. The performance metrics have improved:

DOMContentLoaded: timestamp 335.7ms --> **315ms**
- Indicates the browser has finished parsing the document, but other resources such as images and stylesheets may/may not have been downloaded
Load event: timestamp 767.9ms --> **641.8ms**
- The load event fired will occur once all the initial resources (images, stylesheets, JavaScript) have been downloaded.

hpe-global-header.js: duration 257ms --> **224.8ms**

**Comment by halocline** [comment] 2022-10-27 19:39
> Re: bundle size, I realized we weren't doing `--mode production` on the webpack build. When we do this, the file size is reduced to 421kB. PR filed: https://github.hpe.com/grommet/hpe-global-header/pull/6
> 
75+% reduction.

What type of encoding does the .js file get shipped as?

**Comment by taysea** [comment] 2022-10-27 19:51
> What type of encoding does the .js file get shipped as?

I believe ascii

<img width="472" alt="Screen Shot 2022-10-27 at 12 50 11 PM" src="https://user-images.githubusercontent.com/12522275/198385113-4654888a-fc3e-41c1-b459-e174b2366c6f.png">

**Comment by taysea** [comment] 2022-10-28 21:36
# Latest Performance Findings

We took the approach of using Brotli as the compression algorithm. Compared to the non-compressed version which takes 87ms for content download, the compressed version only takes 2.31ms.


## JS (non-compressed) version: https://storage.googleapis.com/hpe-global-header-assets/hpe-global-header.js

![Image](https://user-images.githubusercontent.com/12522275/198736273-583c7af8-9ef3-4e41-bdf3-d9f0738c0bb0.png)

## Brotli compressed version: https://storage.googleapis.com/hpe-global-header-assets/hpe-global-header.js.br

![Image](https://user-images.githubusercontent.com/12522275/198736877-3c263916-47aa-48ff-a67d-6a762a0693ba.png)


In theory, the CDN should be able to automatically compress our JS files and honor the browser's request headers. However, we ran into issues getting this configured properly. Through [reading some docs](https://cloud.google.com/cdn/docs/dynamic-compression), it seems like we need to serve our CDN over HTTPS which requires SSL certificates to be generated/maintained.

**Comment by ericsoderberghp** [comment] 2022-10-31 16:55
Excellent progress!!!

**Comment by ericsoderberghp** [comment] 2022-10-31 16:57
Have we verified that we are importing icons efficiently? It looks like we might be pulling in more icons than we need.

**Comment by taysea** [comment] 2022-10-31 17:02
Will look into that. Next steps felt like looking into how we might be able to explore more efficient ways to import/load components within the Global Header, so agreed!

**Comment by ericsoderberghp** [comment] 2022-10-31 17:02
Also, is there a way to look inside the src index.js + 121 modules to see what's driving the size of that's bucket?

**Comment by ericsoderberghp** [comment] 2022-11-02 17:56
Here are a few more things I've learned ...
- The way we do theming means we pull in all of the theme even if only use a handful of components.
  - base.js is 45KB and the hpe theme is 40KB
  - We pull in more icons than we really need
- We should consider breaking up styles.js into multiple files so that we don't have to pull it all in.
- We should look into more lazily loading the drop contents of HelpDropButton and AppsDropButton.
  - The contents of those drops are what end up pulling in Form, Select, TextInput, etc. which are the larger grommet components in terms of source size.

**Comment by taysea** [comment] 2022-11-08 00:02
Initial evaluation has been documented above. Any subsequent evaluations can be tagged onto here in the future or opened in a new ticket.

**Closed by taysea** 2022-11-08 00:02 UTC
