### ISSUE TITLE
Update Card examples to render as buttons, including hover indicator behavior

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#1270] opened 2020-11-18 23:04 UTC
- [ ] Ensure hover and focus behavior is defined in the theme.
- [ ] more ...

**Comment by ericsoderberghp** [comment] 2021-02-16 16:39
Duplicate of https://github.com/grommet/hpe-design-system/issues/1390

**Closed by ericsoderberghp** 2021-02-16 16:39 UTC
Labels: Implement, design system site
