### ISSUE TITLE
Layer - add layer layout guidance

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#2409] opened 2022-03-01 19:43 UTC
Provide general layout guidance for Layers akin to what we've done for Page Layouts.

- [ ] Figma updates as needed, see https://www.figma.com/file/Ts53TAipMolmsv9DxWG3p0/HPE-Layer-Component?node-id=0%3A1
- [ ] review with team
- [ ] enhance design system site to include

**Comment by vavalos5** [comment] 2022-05-23 20:16
We'll want to look at the close icon too and if there are every any recommendations on when we should or shouldn't use it. I've seen some designs across services where they're not implementing them and it could be due to discrepancies between the design systems site and Figma.

**Comment by taysea** [comment] 2022-11-21 20:22
Closing as this feels like a duplicate of #3019

**Closed by taysea** 2022-11-21 20:22 UTC
Labels: design system site, design
